spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: versionwen #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /price/**
      - /minio/**
      - /user/**
logging:
  level:
    root: info
    com:
      wenxin:
        learn:
          faststart:
            web:
              mapper: debug
              config: debug
